-- Optional: enable UUID generation extension (though IDs will come from the app)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE classifications (
    id                    UUID PRIMARY KEY NOT NULL,          -- UUID v7 generated by app
    name                  VARCHAR NOT NULL UNIQUE,             -- Case-sensitive unique per spec
    gender                VARCHAR NOT NULL,                    -- 'male' or 'female', not an enum
    gender_probability    FLOAT NOT NULL CHECK (gender_probability >= 0 AND gender_probability <= 1),
    age                   INTEGER NOT NULL CHECK (age >= 0),
    age_group             VARCHAR NOT NULL,                    -- child, teenager, adult, senior
    country_id            VARCHAR(2) NOT NULL,                 -- ISO 3166-1 alpha-2 code
    country_name          VARCHAR NOT NULL,                    -- Full country name
    country_probability   FLOAT NOT NULL CHECK (country_probability >= 0 AND country_probability <= 1),
    created_at            TIMESTAMP NOT NULL DEFAULT NOW()     -- Timestamp without time zone
);

-- Optional index for faster lookups by country_id
CREATE INDEX classifications_country_id_idx ON classifications (country_id);